# = Gemfile containing requirements for this app =
#     see http://gembundler.com/ for more on how to use this file
# source (there are others but whatever)
source 'https://rubygems.org'

# let's use WEBrick
# # server
# gem 'mongrel'

# rack
gem 'rack', '1.5.2'
gem 'rake', '10.0.3'

# sinatra
gem 'sinatra', '1.4.5'
gem 'sinatra-asset-pipeline'
gem 'sinatra-contrib', '1.4.2'
gem 'sinatra-index'
gem 'json', '1.8.0'

# sqlite
gem 'sqlite3'
gem 'activerecord'

gem 'coffee-script'
gem 'haml', '4.0.0'
gem 'kss'
gem 'sass'
gem 'uglifier', '1.3.0'
