# = Gemfile containing requirements for this app =
#     see http://gembundler.com/ for more on how to use this file
# source (there are others but whatever)
source 'https://rubygems.org'
ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.18'
# let's use WEBrick
# # server
# gem 'mongrel'

# rack
gem 'rack', '1.5.2'
gem 'rake', '10.0.3'

# sinatra
gem 'sinatra', '1.4.5'
gem 'sinatra-asset-pipeline'
gem 'sinatra-contrib', '1.4.2'
gem 'sinatra-index'
gem 'json'

# sqlite
gem 'activerecord-jdbc-adapter'
gem 'activerecord-jdbcsqlite3-adapter'
gem 'activerecord'

gem 'coffee-script'
gem 'haml', '4.0.0'
gem 'haute', '~> 0.2.1'
gem 'sass'
gem 'uglifier', '1.3.0'
